In [9]:
import torch
import math

In [26]:
position = torch.arange(0, 5).unsqueeze(1)
position

tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [24]:
div = torch.exp(torch.arange(0,15,2).float()*(-math.log(10000.0)/15))
div

tensor([1.0000e+00, 2.9286e-01, 8.5770e-02, 2.5119e-02, 7.3564e-03, 2.1544e-03,
        6.3096e-04, 1.8479e-04])

In [36]:
position * div

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [1.0000e+00, 2.9286e-01, 8.5770e-02, 2.5119e-02, 7.3564e-03, 2.1544e-03,
         6.3096e-04, 1.8479e-04],
        [2.0000e+00, 5.8573e-01, 1.7154e-01, 5.0238e-02, 1.4713e-02, 4.3089e-03,
         1.2619e-03, 3.6957e-04],
        [3.0000e+00, 8.7859e-01, 2.5731e-01, 7.5357e-02, 2.2069e-02, 6.4633e-03,
         1.8929e-03, 5.5436e-04],
        [4.0000e+00, 1.1715e+00, 3.4308e-01, 1.0048e-01, 2.9426e-02, 8.6177e-03,
         2.5238e-03, 7.3914e-04]])

In [22]:
pe = torch.zeros(5, 15)
pe

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
s = torch.sin(position * div)
s

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 8.4147e-01,  2.8870e-01,  8.5664e-02,  2.5116e-02,  7.3564e-03,
          2.1544e-03,  6.3096e-04,  1.8479e-04],
        [ 9.0930e-01,  5.5281e-01,  1.7070e-01,  5.0217e-02,  1.4712e-02,
          4.3089e-03,  1.2619e-03,  3.6957e-04],
        [ 1.4112e-01,  7.6984e-01,  2.5448e-01,  7.5285e-02,  2.2067e-02,
          6.4633e-03,  1.8929e-03,  5.5436e-04],
        [-7.5680e-01,  9.2132e-01,  3.3639e-01,  1.0031e-01,  2.9421e-02,
          8.6176e-03,  2.5238e-03,  7.3914e-04]])

In [32]:
pe[:, 0::2] = s

In [33]:
pe

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 8.4147e-01,  0.0000e+00,  2.8870e-01,  0.0000e+00,  8.5664e-02,
          0.0000e+00,  2.5116e-02,  0.0000e+00,  7.3564e-03,  0.0000e+00,
          2.1544e-03,  0.0000e+00,  6.3096e-04,  0.0000e+00,  1.8479e-04],
        [ 9.0930e-01,  0.0000e+00,  5.5281e-01,  0.0000e+00,  1.7070e-01,
          0.0000e+00,  5.0217e-02,  0.0000e+00,  1.4712e-02,  0.0000e+00,
          4.3089e-03,  0.0000e+00,  1.2619e-03,  0.0000e+00,  3.6957e-04],
        [ 1.4112e-01,  0.0000e+00,  7.6984e-01,  0.0000e+00,  2.5448e-01,
          0.0000e+00,  7.5285e-02,  0.0000e+00,  2.2067e-02,  0.0000e+00,
          6.4633e-03,  0.0000e+00,  1.8929e-03,  0.0000e+00,  5.5436e-04],
        [-7.5680e-01,  0.0000e+00,  9.2132e-01,  0.0000e+00,  3.3639e-01,
          0.0000e+00,  1.0031e-01,

In [47]:
mat = torch.arange(10)[None] - torch.arange(10)[:,None]
mat

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [-1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
        [-2, -1,  0,  1,  2,  3,  4,  5,  6,  7],
        [-3, -2, -1,  0,  1,  2,  3,  4,  5,  6],
        [-4, -3, -2, -1,  0,  1,  2,  3,  4,  5],
        [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
        [-6, -5, -4, -3, -2, -1,  0,  1,  2,  3],
        [-7, -6, -5, -4, -3, -2, -1,  0,  1,  2],
        [-8, -7, -6, -5, -4, -3, -2, -1,  0,  1],
        [-9, -8, -7, -6, -5, -4, -3, -2, -1,  0]])

In [42]:
torch.arange(8)[:,None]

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7]])

In [48]:
torch.clamp(mat, -4, 4) + 4

tensor([[4, 5, 6, 7, 8, 8, 8, 8, 8, 8],
        [3, 4, 5, 6, 7, 8, 8, 8, 8, 8],
        [2, 3, 4, 5, 6, 7, 8, 8, 8, 8],
        [1, 2, 3, 4, 5, 6, 7, 8, 8, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 8],
        [0, 0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 0, 0, 1, 2, 3, 4, 5, 6, 7],
        [0, 0, 0, 0, 1, 2, 3, 4, 5, 6],
        [0, 0, 0, 0, 0, 1, 2, 3, 4, 5],
        [0, 0, 0, 0, 0, 0, 1, 2, 3, 4]])

In [1]:
from nlhappy.layers.embedding.position_embedding import SinusoidalPositionEmbedding

ModuleNotFoundError: No module named 'transformers'