In [2]:
import torch

In [8]:
ts = torch.randn(2, 3)

In [9]:
ts[ts.gt(0)]

tensor([1.3104, 0.7689])

In [13]:
indice = torch.where(ts>0)
indice

(tensor([0, 1]), tensor([0, 0]))

In [12]:
ts[indice]

tensor([1.3104, 0.7689])